/*
 * This file is generated by jOOQ.
*/
package com.kicinger.domain.tables;


import com.kicinger.domain.Indexes;
import com.kicinger.domain.Keys;
import com.kicinger.domain.Public;
import com.kicinger.domain.tables.records.StateRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class State extends TableImpl<StateRecord> {

    private static final long serialVersionUID = 661740776;

    /**
     * The reference instance of <code>public.state</code>
     */
    public static final State STATE = new State();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StateRecord> getRecordType() {
        return StateRecord.class;
    }

    /**
     * The column <code>public.state.id</code>.
     */
    public final TableField<StateRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.CHAR(2).nullable(false), this, "");

    /**
     * The column <code>public.state.name</code>.
     */
    public final TableField<StateRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * Create a <code>public.state</code> table reference
     */
    public State() {
        this(DSL.name("state"), null);
    }

    /**
     * Create an aliased <code>public.state</code> table reference
     */
    public State(String alias) {
        this(DSL.name(alias), STATE);
    }

    /**
     * Create an aliased <code>public.state</code> table reference
     */
    public State(Name alias) {
        this(alias, STATE);
    }

    private State(Name alias, Table<StateRecord> aliased) {
        this(alias, aliased, null);
    }

    private State(Name alias, Table<StateRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.STATE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<StateRecord> getPrimaryKey() {
        return Keys.STATE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<StateRecord>> getKeys() {
        return Arrays.<UniqueKey<StateRecord>>asList(Keys.STATE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public State as(String alias) {
        return new State(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public State as(Name alias) {
        return new State(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public State rename(String name) {
        return new State(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public State rename(Name name) {
        return new State(name, null);
    }
}
