/*
 * This file is generated by jOOQ.
*/
package com.kicinger.domain;


import com.kicinger.domain.tables.Person;
import com.kicinger.domain.tables.State;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PK_PERSON = Indexes0.PK_PERSON;
    public static final Index STATE_PKEY = Indexes0.STATE_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PK_PERSON = Internal.createIndex("pk_person", Person.PERSON, new OrderField[] { Person.PERSON.ID }, true);
        public static Index STATE_PKEY = Internal.createIndex("state_pkey", State.STATE, new OrderField[] { State.STATE.ID }, true);
    }
}
